### ISSUE TITLE
Running the Install.ps1 file via Powershell does nothing

### ISSUE THREAD

**Issue by capella07** [LSPosed/MagiskOnWSA#143]
I'm not sure if this is the proper place to put this, but I don't see anywhere else to get help with trying to install this.

I'm following [this article on Android Authority](https://www.androidauthority.com/how-to-install-google-play-store-on-windows-11-3049609/) to be able to install the Google Play Store on my Win 11 computer.

I'm good through the point where you extract the downloaded file.

The next step is to right click the "Install" file. Their image says "install", but I have a file "Install.ps1", so I'm assuming they don't have the View File Extenstions on.

Anyway, it says you're supposed to right click the Install file and run it with Powershell. Which I did. The PS window pops up and then closes very quickly, making me think nothing really happened. It's supposed to have installed WSA and the article says to search for it in the Start Menu after doing the Powershell install.

I did a Win + S search for Windows Subsystem and there is no such program on my computer.

Am I doing something wrong?

**Comment by alex-sandro92** [comment]
Open Powershell and check if WSA is installed:

`Get-AppxPackage -name "MicrosoftCorporationII.WindowsSubsystemForAndroid"`


If it is installed it will show you the details of the WSA package, otherwise it will show nothing.
In the first case you can try to remove it with this command:

`Remove-AppxPackage -Package "MicrosoftCorporationII.WindowsSubsystemForAndroid"`

**Comment by yujincheng08** [comment]
Its most likely you are not the administrator of the device and the script cannot evaluate itself as an administrator.

**Comment by capella07** [comment]
Why was this closed when you have no idea whether my issue is resolved or not??

I am the administrator - and only user - of the computer that I am trying to do this on. I got nothing when I ran the above command.

**Comment by yujincheng08** [comment]
Because it cannot be fixed by us. The script will prompt a UAC request as soon as it launches and you didn't get that. That means our script failed to gain the Administrator's permission or even worse it didn't run at all.

In any case, it's not our problem.

PS: the script should show an error if it's failed to get the permission. But anyway for this guy #137 it does not show.
