### ISSUE TITLE
Powershell not opening 

### ISSUE THREAD

**Issue by RaagPRO** [LSPosed/MagiskOnWSA#279]
when i try to open the .ps1, file powershell opens for a second and then crashes

**Comment by yujincheng08** [comment]
please try for a manual inatallation

**Comment by Hitomi98** [comment]
Update: I figured this out by manually open a powershell window, navigate to the directory and then run the script which gave me an error about the execution policy.
Turns out this was the problem.

For someone reading this in the future:
I opened a new powershell window (admin) `Set-ExecutionPolicy Unrestricted` and then was able to run the powershell script again normally.
