### ISSUE TITLE
High usage ram

### ISSUE THREAD

**Issue by AlainEddine** [LSPosed/MagiskOnWSA#29]
This wsa use more ram then normal

**Comment by yujincheng08** [comment]
I think this is bug of WSA instead of ours

**Comment by AlainEddine** [comment]
I dont know but usage ram high then normal wsa from official

**Comment by ray2301** [comment]
what does "uses more ram than normal" mean? for me it's normal that it uses 77% of my 16 GB RAM as it's a virtual subsystem and I installed GApps so it should use more RAM than the official WSA because those services are running. My VmmemWSA process uses about 2,3 - 2,7 GB of RAM and my Windows Subsystem for Android currently uses 94,4 MB of RAM because I only have one android app opened. Everything else are my windows processes so I wouldn't say it uses too much of RAM.
