### ISSUE TITLE
Turned off parallel downloads in edge before attempting to download artifact, DL still fails

### ISSUE THREAD

**Issue by Bareno** [LSPosed/MagiskOnWSA#363]
I've followed every step in the installation process, including disabling multithreading in edge to my knowledge (edge://flags/, then searching and disabling the "Parallel downloading" flag), but for some reason the github artifact still seems to fail to download, as in anywhere from like 5 seconds into the download to like a minute the download progress ends up at 0 B/s. Is there a program or something else that is more reliable to download the artifact? Thanks!

**Comment by Howard20181** [comment]
Use a proxy.

**Comment by PeterNjeim** [comment]
@Bareno artifacts are terrible for downloading. Not sure why you disabled parallel downloading, set that back to the default. Use Releases instead. Fork my repo from [here](https://github.com/PeterNjeim/MagiskOnWSA) and run the Action as you normally would, except when it's finished go to the Releases page and download it from there (in the assets). Or alternatievely, if you want pico GApps and stable Magisk, go to the Releases page on my repo and download it from there since I've already built it. no Action or fork needed.
