### ISSUE TITLE
The Zip file not download complete from GitHub

### ISSUE THREAD

**Issue by thecientific** [LSPosed/MagiskOnWSA#462]
I have the following issue, when I try download the file WSA-with-magisk-NoGApps_2205.40000.14.0_x64_Release-Nightly.zip show complete from 700mb to 800mb, I try use different computer and different internet provider, same result. The question is, GitHub place limit download for big files?

**Comment by cp6tbix0r** [comment]
Same. I wonder why. I followed the instructions to not download it with idm or adm.. like don't download it with threads or whatever.
I'm using Chrome and it's still only letting me download 300mb and then fails. 

Why don't they just use a free file hoster with an API? So it will upload the artifact automatically after running an action workflow? Idk. I don't understand? Sorry.. (When running again, it can just delete the file that has been uploaded, so it won't waste any storage on the file hoster), so we don't need to fork it. It's kind of abusing GitHub resources if it goes on like this, because so many people that don't know anything about GitHub, like me, make an account just to run that action workflow and then forget about the account, also forget to delete the repo and the workflow.

**Comment by yujincheng08** [comment]
@thecientific its possible that the workflow has corrupted artifacts. Try to rerun the workflow.

**Comment by cp6tbix0r** [comment]
![Screenshot_20220712-114120_Soul](https://user-images.githubusercontent.com/109055837/178410194-6f515942-d5c3-4fe6-ba92-a4a2ef2a59aa.png) 
@yujincheng08 I'm sorry, it still doesn't work even though I've tried to rerun it and download it again. Thanks though.

**Comment by Howard20181** [comment]
> ![Screenshot_20220712-114120_Soul](https://user-images.githubusercontent.com/109055837/178410194-6f515942-d5c3-4fe6-ba92-a4a2ef2a59aa.png) 
> @yujincheng08 I'm sorry, it still doesn't work even though I've tried to rerun it and download it again. Thanks though.

Use your browser's built-in downloader and do not use multi-threaded downloads.

**Comment by cp6tbix0r** [comment]
Yes, that's what I've been using to download the artifact.. even Chrome doesn't work..

**Comment by Howard20181** [comment]
> Yes, that's what I've been using to download the artifact.. even Chrome doesn't work..

Try https://github.com/LSPosed/MagiskOnWSA/actions/runs/2653301699

**Comment by cp6tbix0r** [comment]
Ok, Thanks!

**Comment by cp6tbix0r** [comment]
It's downloaded successfully on the Edge Browser. It's just weird. Isn't Edge cromium-based? Why does Chrome always fail? But-- well, thanks anyway.

![Screenshot_20220712-151032_Edge](https://user-images.githubusercontent.com/109055837/178442817-6567ce7d-5394-4224-915c-a7e113a4c46e.png)
