### ISSUE TITLE
install.ps1 file instantly closes when ran w/ powershell

### ISSUE THREAD

**Issue by Quinten0508** [LSPosed/MagiskOnWSA#59]
Running Win11 Pro - Dev Build 22483.1011
The powershell window immediately closes, no UAC prompt pops up, WSA isn't installed.

**Comment by Hasanajouz** [comment]
I think it is related to this error
I will check and try to find a solution 
because me too I am facing this problem
The file  is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.

**Comment by Hasanajouz** [comment]
Run this command on PowerShell and the script will run:
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

**Comment by Quinten0508** [comment]
Yup, that works! I did Unblock-File -Path <path to .ps1 file> in an elevated PS prompt so I don't have to re-enable the security policy afterwards, but both should work. Thank you!

**Comment by tuviaido** [comment]
And after that, Click yes or no?

**Comment by Quinten0508** [comment]
> And after that, Click yes or no?

You can't click on a command line, but just read what they ask you and what options you have, it should be obvious that you don't want to cancel the command or something similar.
